"""Subclass of Settings, which is generated by wxFormBuilder."""

import wx
import TheDictionary

# Implementing Settings
class TheDictionarySettings( TheDictionary.Settings ):
	def __init__( self, parent ):
		TheDictionary.Settings.__init__( self, parent )

